### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/io.ionic.starter/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by ZooLeeCoding** [gaganinvic/cordova-plugin-jitsi-meet#1]
`java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/io.ionic.starter/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit`

This is the error code I receive, when trying to run the Ionic application with this plugin on Android 7.0. I'm trying to call the loadURL method on my main page in the constructor, without the plugin or specifically, without calling the loadURL method everything works fine. The app immediately crashes after the splashscreen disappeared.

I'm trying to use some solutions I've found on stackoverflow to get 32-bit libraries running on a 64-bit system (like this: https://stackoverflow.com/questions/30782848/how-to-use-32-bit-native-libraries-on-64-bit-android-device?lq=1) but no luck so far.

What am I doing wrong?

**Comment by gaganinvic** [comment]
I added the fix. This should help. Let me know how it goes

**Comment by ZooLeeCoding** [comment]
Works perfectly. Thank you :)

**Comment by gaganinvic** [comment]
Perfect
