### ISSUE TITLE
Non-whitespace before first tag

### ISSUE THREAD

**Issue by dimitri-guitton** [gaganinvic/cordova-plugin-jitsi-meet#7]
Hi,

When I trie to install your plugin with this command `ionic cordova plugin add https://github.com/gaganinvic/cordova-plugin-jitsi-meet`
I got this errror in my terminal
```
Non-whitespace before first tag.
Line: 0
Column: 1
Char: ¬
[ERROR] An error occurred while running subprocess cordova.
```
In the beginning, I think it was my config.xml that have a syntax error, but when I try to install an another plugin its work fine. So I check your plugin.xml and first character is a `¬`
I don't know if this character is correct but if that's case what is the correct method to install your plugin.

Best regards

**Comment by jrajba** [comment]
any news about that issue? 
I have the same problem

**Comment by dimitri-guitton** [comment]
> any news about that issue?
> I have the same problem

Hi, There is a lot of Fork that fixes the problem. I used this one https://github.com/MedZghal/cordova-plugin-jitsi-meet

**Comment by jrajba** [comment]
Thx:)

pon., 20 sty 2020, 09:55 użytkownik Dimitri <notifications@github.com>
napisał:
